### PR TITLE
Added Communtity Assets

### PR DESCRIPTION
**Pull request by Mannuel25**
**Issue No**: #20 

**What does this PR do?:**

Addition of community assets to the repository. I also added the contributions guidelines link to `pull_request_template.md`

**Description of Task to be completed?**

> * [x]  Logo - yellow
> * [x]  Logo - white
> * [x]  Logo - black
> * [x]  Banner logo
> * [x]  Banner animation

**Have you read the <a href="">contribution Guidelines</a>?**

- [x] Yes
- [ ] No

### CODE REVIEW

**Review by Evavic44 — APPROVED** [review]
LGTM! 👍🏾

**Review by Evavic44 — CHANGES_REQUESTED** [review]
Did you test this link to see if it works? Would be better to paste the complete URL, like this

`<a href="https://github.com/CommunityPro/support/blob/main/CONTRIBUTING.md">contribution guideline</a>`

**Comment by Mannuel25** [comment]
> Did you test this link to see if it works? Would be better to paste the complete URL, like this
> 
> `<a href="https://github.com/CommunityPro/support/blob/main/CONTRIBUTING.md">contribution guideline</a>`

Oh, wow. Yes I did. I'll make adjustments now. Thanks.

**Comment by Mannuel25** [comment]
> Did you test this link to see if it works? Would be better to paste the complete URL, like this
> 
> `<a href="https://github.com/CommunityPro/support/blob/main/CONTRIBUTING.md">contribution guideline</a>`

Made necessary changes, kindly check it out.

**Review by Evavic44 — APPROVED** [review]
LGTM! 👍🏾

**Review by Evavic44 — APPROVED** [review]
Awesome job. 👍🏾

**Pull request merged**
